Improve performance with CharacterOptionExtensions
ACEmulator/ACE pull request #4206
Opened 2024-07-23 03:36 UTC by FlaggAC

Improves performance with CharacterOptionExtensions. There is some overhead with calling GetAttributeOfType, so we are pre-caching these results.

Moves CharacterOptionExtensions from ACE.Entity to ACE.Server, as ACE.Entity's .NET Standard doesn't support FrozenDictionary or Enum.GetValues<T>.

I could rewrite this in a way that is compatible with .NET Standard, but it seemed more appropriate for the class to be in ACE.Server anyway so I moved it for now.

2024-07-23 11:44 UTC, Mag-nus requested changes

2024-07-23 11:44 UTC, Mag-nus commented on Source/ACE.Server/Entity/CharacterOptionExtensions.cs
CharacterOptionExtensions should either remain in CharacterOptions.cs, or, if it is to be a separate file, it should be in the same folder as CharacterOptions.cs

Also, standard ACE using format is System on top, ACE below, separated by a space, ie:

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

using ACE.Entity;
using ACE.Entity.Enum;

2024-07-23 14:33 UTC, gmriggs commented
where did CharacterOptionExtensions sit in the profile of the entire server?

before/after benchmarks for these changes?

2024-07-24 02:03 UTC, Mag-nus approved these changes

2024-07-25 13:32 UTC, merged